# Generated by Django 5.2.4 on 2026-07-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('constructor_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('points', models.DecimalField(decimal_places=1, max_digits=7)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('driver_id', models.CharField(max_length=80, unique=True)),
                ('given_name', models.CharField(max_length=80)),
                ('family_name', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('constructor', models.CharField(max_length=120)),
                ('points', models.DecimalField(decimal_places=1, max_digits=7)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(unique=True)),
                ('race_name', models.CharField(max_length=160)),
                ('circuit_name', models.CharField(max_length=160)),
                ('locality', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('race_start_at', models.DateTimeField()),
                ('first_practice_at', models.DateTimeField(blank=True, null=True)),
                ('second_practice_at', models.DateTimeField(blank=True, null=True)),
                ('third_practice_at', models.DateTimeField(blank=True, null=True)),
                ('qualifying_at', models.DateTimeField(blank=True, null=True)),
                ('sprint_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['race_start_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('next_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('apparent_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('summary', models.CharField(blank=True, max_length=120)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='dashboard.race')),
            ],
        ),
    ]
