# Generated by Django 5.2.4 on 2026-07-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverstanding',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.DeleteModel(
            name='WeatherSnapshot',
        ),
    ]
