# Generated by Django 5.2.4 on 2026-07-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_driverstanding_nationality_delete_weathersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('race_name', models.CharField(max_length=160)),
                ('circuit_name', models.CharField(max_length=160)),
                ('date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('grid', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('constructor', models.CharField(blank=True, max_length=120)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.driverstanding')),
            ],
            options={
                'ordering': ['round'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'round'), name='unique_driver_result_round')],
            },
        ),
    ]
